import turtle
pen=turtle.Turtle()
screen=turtle.Screen()
pen.color("red")  
pen.speed("slow") 
pen.forward(120)
pen.left(60)
pen.forward(180)
pen.right(270)
pen.forward(180)
pen.left(60)
pen.forward(180)
pen.left(90)
pen.forward(180)
screen.exitonclick()